version: "3.8"
services:
  db:
    image: postgres:15
    container_name: inventory-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: inventory-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      # DATABASE_URL: postgresql://postgres:root@localhost:5432/inventorymanagement?schema=public
      DATABASE_URL: postgresql://postgres:postgres@db:5432/inventory
      
  frontend:
    build: ./client
    container_name: inventory-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000

volumes:
  postgres_data: