apiVersion: v2
name: inventory
description: Helm chart to deploy Inventory application (Postgres, Backend, Frontend) on EKS
type: application
version: 0.1.0
appVersion: "1.0.0"
kubeVersion: ">=1.24.0-0"